# Generated by Django 4.2 on 2025-03-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_alter_employeeprofile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelapplication',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
