# Generated by Django 4.2 on 2025-03-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0006_travelapplication_employee_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelapplication',
            name='has_manager_notes',
            field=models.BooleanField(default=False),
        ),
    ]
